/*
 * loquat-prim test / prim.updateParserState()
 * copyright (c) 2016 Susisu
 */

"use strict";

const chai = require("chai");
const expect = chai.expect;

const SourcePos    = _core.SourcePos;
const ParseError   = _core.ParseError;
const Config       = _core.Config;
const State        = _core.State;
const Result       = _core.Result;
const assertParser = _core.assertParser;

const updateParserState = _prim.updateParserState;

describe(".updateParserState(func)", () => {
    it("should return a parser that sets parser state to the state generated by `func' and empty succeeds", () => {
        const initState = new State(
            new Config({ tabWidth: 8 }),
            "input",
            new SourcePos("foobar", 1, 1),
            "none"
        );
        const newState = new State(
            new Config({ tabWidth: 4 }),
            "rest",
            new SourcePos("foobar", 1, 2),
            "some"
        );
        const parser = updateParserState(state => {
            expect(State.equal(state, initState)).to.be.true;
            return newState;
        });
        assertParser(parser);
        const res = parser.run(initState);
        expect(Result.equal(
            res,
            Result.esuc(
                ParseError.unknown(newState.pos),
                newState,
                newState
            )
        )).to.be.true;
    });
});
